### ISSUE TITLE
please add lambda-admin.template to Snowplow hosted S3 accessible to public

### ISSUE THREAD

**Issue by bigsnarfdude** [snowplow/aws-lambda-nodejs-example-project#16]
https://github.com/snowplow/aws-lambda-nodejs-example-project/blob/attempt2/resources/lambda-admin.template

**Comment by alexanderdean** [comment]
Done, https://snowplow-hosted-assets.s3.amazonaws.com/third-party/aws-lambda/lambda-admin.template
