### ISSUE TITLE
aws cli missing from vagrant

### ISSUE THREAD

**Issue by bigsnarfdude** [snowplow/aws-lambda-nodejs-example-project#7]
The program 'aws' is currently not installed. To run 'aws' please ask your administrator to install the package 'awscli'
vagrant@aws-lambda-example-project:/vagrant$

**Comment by alexanderdean** [comment]
https://github.com/snowplow/spark-streaming-example-project/blob/master/vagrant/up.playbooks#L1

**Comment by bigsnarfdude** [comment]
modified playbook tested. working now
